name: Issue report
description: Report a source issue in LNReader
labels: [Bug]
body:
  - type: dropdown
    id: source
    attributes:
      label: Plugin
      description: Select the plugin associated with the issue.
      multiple: true
      options:
        - "‎العربية: ArNovel"
        - "‎العربية: Azora"
        - "‎العربية: dilar tube"
        - "‎العربية: HizoManga"
        - "‎العربية: Kol Novel"
        - "‎العربية: Novel4Up"
        - "‎العربية: Novels Paradise"
        - "‎العربية: Olaoe.cyou"
        - "‎العربية: Rewayat Club"
        - "‎العربية: Riwyat"
        - "‎العربية: Sunovels"
        - "中文, 汉语, 漢語: 69书吧"
        - "中文, 汉语, 漢語: Linovelib"
        - "中文, 汉语, 漢語: Linovelib(繁體)"
        - "English: FirstKissNovel"
        - "English: AllNovel"
        - "English: AllNovelFull"
        - "English: Arcane Translations"
        - "English: Archive Of Our Own"
        - "English: Srank Manga"
        - "English: Belle Reservoir"
        - "English: BestLightNovel"
        - "English: BoxNovel"
        - "English: Chrysanthemum Garden"
        - "English: Citrus Aurora"
        - "English: Coral Boutique"
        - "English: CPUnovel"
        - "English: Daoist Quest"
        - "English: DaoNovel"
        - "English: DaoTranslate"
        - "English: Divine Dao Library"
        - "English: Dragon Tea"
        - "English: Dream Big Translations"
        - "English: Dusk Blossoms"
        - "English: Early Novel"
        - "English: ElloTL"
        - "English: Eternalune"
        - "English: FanNovel"
        - "English: Fans Translations"
        - "English: Fenrir Translations"
        - "English: Fiction Zone"
        - "English: Foxaholic"
        - "English: Foxteller"
        - "English: Faq Wiki"
        - "English: Free Web Novel"
        - "English: Galaxy Translations"
        - "English: Genesis"
        - "English: Guavaread"
        - "English: Hiraeth Translation"
        - "English: HotNovelPub"
        - "English: Inkitt"
        - "English: Ippotranslations"
        - "English: Keopi Translations"
        - "English: KnoxT"
        - "English: Lazy Girl Translations"
        - "English: Lib Read"
        - "English: LightNovelCave"
        - "English: LightNovelPlus"
        - "English: LightNovelPub"
        - "English: LightNovelPub Vip"
        - "English: Light Novel Updates"
        - "English: LightNovelWord"
        - "English: Lily on the Valley"
        - "English: LightNovelHeaven"
        - "English: LnMTL"
        - "English: Ltnovel"
        - "English: LunarLetters"
        - "English: Meownovel"
        - "English: Moonlight Novels"
        - "English: MostNovel"
        - "English: MTL-Novel"
        - "English: MTL Novel"
        - "English: MTL Reader"
        - "English: MVLEMPYR"
        - "English: MysticalSeries"
        - "English: NeoSekai Translations"
        - "English: Nitro Manga"
        - "English: novelsOnline"
        - "English: NobleMTL"
        - "English: Novel Bin"
        - "English: NovelBuddy.io"
        - "English: Novel Fire"
        - "English: NovelFull"
        - "English: Novel Hall"
        - "English: NovelLib"
        - "English: Novelight"
        - "English: NovelMultiverse"
        - "English: NovelsKnight"
        - "English: NovelTranslate"
        - "English: Novel Updates"
        - "English: Panda Machine Translations"
        - "English: Pastel Tales"
        - "English: PawRead"
        - "English: Rainofsnow"
        - "English: Ranobes"
        - "English: Read Fanfic"
        - "English: Read From Net"
        - "English: ReadNovelFull"
        - "English: Re:Library"
        - "English: Requiem Translations"
        - "English: ReadLiteNovel"
        - "English: Royal Road"
        - "English: Salmon Latte"
        - "English: Scribble Hub"
        - "English: SleepyTranslations"
        - "English: SonicMTL"
        - "English: StorySeedling"
        - "English: Sweet Escape"
        - "English: System Translation"
        - "English: TranslatinOtaku"
        - "English: Universal Novel"
        - "English: Vandy Translate"
        - "English: Violet Lily"
        - "English: VyNovel"
        - "English: Webnovel"
        - "English: WebNovelLover"
        - "English: Web Novel Pub"
        - "English: White Moonlight Novels"
        - "English: Wook's Teahouse"
        - "English: WordExcerpt"
        - "English: WTR-LAB"
        - "English: Wuxiafox"
        - "English: Fans MTL"
        - "English: Wuxiabox"
        - "English: Wuxia Space"
        - "English: WuxiaV"
        - "English: Wuxia World"
        - "English: WuxiaWorld.Site"
        - "English: Zetro Translation"
        - "Français: Chireads"
        - "Français: HarkenEliwood"
        - "Français: KissWood"
        - "Français: Ligh Novel FR"
        - "Français: MTL Novel (FR)"
        - "Français: NovelDeGlace"
        - "Français: Novhell"
        - "Français: PhenixScans"
        - "Français: Warrior Legend Trad"
        - "Français: WorldNovel"
        - "Français: WuxiaLnScantrad"
        - "Français: Xiaowaz"
        - "Bahasa Indonesia: Baca Light Novel"
        - "Bahasa Indonesia: IndoWebNovel"
        - "Bahasa Indonesia: MeioNovel"
        - "Bahasa Indonesia: Risenovel"
        - "Bahasa Indonesia: MTL Novel (ID)"
        - "Bahasa Indonesia: NovelBookID"
        - "Bahasa Indonesia: NovelRingan"
        - "Bahasa Indonesia: SakuraNovel"
        - "Bahasa Indonesia: Sekte Novel"
        - "Bahasa Indonesia: WBNovel"
        - "日本語: kakuyomu"
        - "日本語: Syosetu"
        - "조선말, 한국어: Agitoon"
        - "조선말, 한국어: Fortune Eternal"
        - "Polski: Novelki"
        - "Português: Better Novels"
        - "Português: Blog do Amon Novels"
        - "Português: Central Novel"
        - "Português: Kiniga"
        - "Português: LaNovels"
        - "Português: Light Novel Brasil"
        - "Português: MTL Novel (PT)"
        - "Português: Novel Mania"
        - "Português: Tsundoku Traduções"
        - "Русский: Автор Тудей"
        - "Русский: Bookhamster"
        - "Русский: Bookriver"
        - "Русский: Erolate"
        - "Русский: EzNovels"
        - "Русский: ficbook"
        - "Русский: LitSpace"
        - "Русский: Свободный Мир Ранобэ"
        - "Русский: Jaomix"
        - "Русский: MTL Novel (RU)"
        - "Русский: Neobook"
        - "Русский: НовелОВХ"
        - "Русский: Ranobes (RU)"
        - "Русский: Renovels"
        - "Русский: RanobeLib"
        - "Русский: RanobeHub"
        - "Русский: РанобэРФ"
        - "Русский: Rulate"
        - "Русский: Ruvers"
        - "Русский: NovelTL"
        - "Русский: ТопЛиба"
        - "Русский: Целлюлоза"
        - "Español: AllNovelRead"
        - "Español: Hasu Translations"
        - "Español: LightNovelDaily"
        - "Español: MTL Novel (ES)"
        - "Español: Novelas Ligera"
        - "Español: Oasis Translations"
        - "Español: Pancho Translations"
        - "Español: ReinoWuxia"
        - "Español: SkyNovels"
        - "Español: Traducciones Amistosas"
        - "Español: TuNovelaLigera"
        - "Español: Yuuki Tls"
        - "ไทย: Novel Lucky"
        - "ไทย: Novel PDF"
        - "Türkçe: Araz Novel"
        - "Türkçe: E-KİTAPLAR"
        - "Türkçe: EpikNovel"
        - "Türkçe: Kodeks Library"
        - "Türkçe: MangaTR"
        - "Türkçe: NABİ SCANS"
        - "Türkçe: Namevt"
        - "Türkçe: Novel oku"
        - "Türkçe: Novelokutr"
        - "Türkçe: NovelTR"
        - "Türkçe: Ragnar Scans"
        - "Türkçe: ThNovels"
        - "Türkçe: TurkceLightNovels"
        - "Türkçe: WebNovelOku"
        - "Українська: BakaInUA"
        - "Українська: Смаколики"
        - "Українська: UA Ranobe Club"
        - "Tiếng Việt: Light Novel VN"
        - "Tiếng Việt: Hako"
        - "Tiếng Việt: Nettruyen"
        - "Tiếng Việt: Truyện Chữ"
        - "Tiếng Việt: Truyen Conect"
        - "Tiếng Việt: Truyện Full"
        - "Multi: Komga"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of the issue you want to report.
      multiple: false
      options:
        - Wrong formatting
        - Wrong content
        - Missing chapter
        - Missing images
        - Can't load novels
        - Other
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: lnreader-version
    attributes:
      label: LNReader version
      description: |
        You can find your LNReader version in **More → About**.
      placeholder: |
        Example: "1.1.19"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: |
        You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 11"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
          required: true
        - label: I have updated all installed extensions.
          required: true
        - label: If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
          required: true
        
