name: Request Feature
description: Suggest an improvement for an existing plugin
labels: [Feature Request]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added.
      placeholder: |
        Example:
          "Add support for latest novels list in Royal Road plugin..."
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other Details
      description: Any additional context or mockups.
      placeholder: |
        Additional information, use cases, or examples.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if these requirements are not met.
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate.
          required: true
        - label: I have written a clear and descriptive title.
          required: true
        - label: I understand that app-specific features should be requested in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
          required: true
        - label: I have updated the app to the latest version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
          required: true
        - label: I have provided all requested information in this form.
          required: true
