name: Request Plugin
description: Request a new plugin for LNReader
labels: [Plugin Request]
body:
  - type: input
    id: name
    attributes:
      label: Plugin Name
      description: The name of the website or platform.
      placeholder: |
        Example: "Novel Updates"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Website URL
      description: The URL of the website.
      placeholder: |
        Example: "https://example.com"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Language
      description: The primary language of the website.
      placeholder: |
        Example: "English"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other Details
      description: Any additional information about the website.
      placeholder: |
        Why this plugin would be useful, special features, etc.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if these requirements are not met.
      options:
        - label: I have searched existing issues and confirmed this plugin has not been requested before.
          required: true
        - label: I have used the plugin name as the issue title.
          required: true
        - label: I have verified this plugin does not already exist in the [repository](https://github.com/LNReader/lnreader-plugins).
          required: true
        - label: I have provided all requested information in this form.
          required: true
