export const languages = {
    Arabic: "العربية",
    Chinese: "中文, 汉语, 漢語",
    English: "English",
    French: "français, française",
    Indonesian: "Bahasa Indonesia",
    Japanese: "日本語",
    Korean: "한국어, 조선말",
    Portuguese: "Português",
    Russian: "русский язык",
    Spanish: "español, castellano",
    Turkish: "Türkçe",
    Ukraine: "Україна",
    Vietnamese: "Tiếng Việt",
} as const;
