export const languages = {
  Arabic: 'العربية',
  Chinese: '中文, 汉语, 漢語',
  English: 'English',
  French: 'Français',
  Indonesian: 'Bahasa Indonesia',
  Japanese: '日本語',
  Korean: '조선말, 한국어',
  Polish: 'Polski',
  Portuguese: 'Português',
  Russian: 'Русский',
  Spanish: 'Español',
  Thai: 'ไทย',
  Turkish: 'Türkçe',
  Ukrainian: 'Українська',
  Vietnamese: 'Tiếng Việt',
} as const;
