export const languages = {
    Arabic: "العربية",
    Chinese: "中文, 汉语, 漢語",
    English: "English",
    French: "Français",
    Indonesian: "Bahasa Indonesia",
    Japanese: "日本語",
    Korean: "조선말, 한국어",
    Portuguese: "Português",
    Russian: "Русский",
    Spanish: "Español",
    Turkish: "Türkçe",
    Ukraine: "Україна",
    Vietnamese: "Tiếng Việt",
} as const;
